//! This code was AUTOGENERATED using the kinobi library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun kinobi to update it.
//!
//! <https://github.com/kinobi-so/kinobi>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use crate::generated::types::GetSwapAmountAndFeesParams;

/// Accounts.
pub struct GetSwapAmountAndFees {
      
              
          pub perpetuals: solana_program::pubkey::Pubkey,
          
              
          pub pool: solana_program::pubkey::Pubkey,
          
              
          pub receiving_custody: solana_program::pubkey::Pubkey,
          
              
          pub receiving_custody_oracle_account: solana_program::pubkey::Pubkey,
          
              
          pub dispensing_custody: solana_program::pubkey::Pubkey,
          
              
          pub dispensing_custody_oracle_account: solana_program::pubkey::Pubkey,
      }

impl GetSwapAmountAndFees {
  pub fn instruction(&self, args: GetSwapAmountAndFeesInstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: GetSwapAmountAndFeesInstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.perpetuals,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.pool,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.receiving_custody,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.receiving_custody_oracle_account,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.dispensing_custody,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.dispensing_custody_oracle_account,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = GetSwapAmountAndFeesInstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::PERPETUALS_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshDeserialize, BorshSerialize)]
pub struct GetSwapAmountAndFeesInstructionData {
            discriminator: [u8; 8],
            }

impl GetSwapAmountAndFeesInstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [247, 121, 40, 99, 35, 82, 100, 32],
                                }
  }
}

impl Default for GetSwapAmountAndFeesInstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetSwapAmountAndFeesInstructionArgs {
                  pub params: GetSwapAmountAndFeesParams,
      }


/// Instruction builder for `GetSwapAmountAndFees`.
///
/// ### Accounts:
///
          ///   0. `[]` perpetuals
          ///   1. `[]` pool
          ///   2. `[]` receiving_custody
          ///   3. `[]` receiving_custody_oracle_account
          ///   4. `[]` dispensing_custody
          ///   5. `[]` dispensing_custody_oracle_account
#[derive(Clone, Debug, Default)]
pub struct GetSwapAmountAndFeesBuilder {
            perpetuals: Option<solana_program::pubkey::Pubkey>,
                pool: Option<solana_program::pubkey::Pubkey>,
                receiving_custody: Option<solana_program::pubkey::Pubkey>,
                receiving_custody_oracle_account: Option<solana_program::pubkey::Pubkey>,
                dispensing_custody: Option<solana_program::pubkey::Pubkey>,
                dispensing_custody_oracle_account: Option<solana_program::pubkey::Pubkey>,
                        params: Option<GetSwapAmountAndFeesParams>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl GetSwapAmountAndFeesBuilder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn perpetuals(&mut self, perpetuals: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.perpetuals = Some(perpetuals);
                    self
    }
            #[inline(always)]
    pub fn pool(&mut self, pool: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.pool = Some(pool);
                    self
    }
            #[inline(always)]
    pub fn receiving_custody(&mut self, receiving_custody: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.receiving_custody = Some(receiving_custody);
                    self
    }
            #[inline(always)]
    pub fn receiving_custody_oracle_account(&mut self, receiving_custody_oracle_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.receiving_custody_oracle_account = Some(receiving_custody_oracle_account);
                    self
    }
            #[inline(always)]
    pub fn dispensing_custody(&mut self, dispensing_custody: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.dispensing_custody = Some(dispensing_custody);
                    self
    }
            #[inline(always)]
    pub fn dispensing_custody_oracle_account(&mut self, dispensing_custody_oracle_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.dispensing_custody_oracle_account = Some(dispensing_custody_oracle_account);
                    self
    }
                    #[inline(always)]
      pub fn params(&mut self, params: GetSwapAmountAndFeesParams) -> &mut Self {
        self.params = Some(params);
        self
      }
        /// Add an aditional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = GetSwapAmountAndFees {
                              perpetuals: self.perpetuals.expect("perpetuals is not set"),
                                        pool: self.pool.expect("pool is not set"),
                                        receiving_custody: self.receiving_custody.expect("receiving_custody is not set"),
                                        receiving_custody_oracle_account: self.receiving_custody_oracle_account.expect("receiving_custody_oracle_account is not set"),
                                        dispensing_custody: self.dispensing_custody.expect("dispensing_custody is not set"),
                                        dispensing_custody_oracle_account: self.dispensing_custody_oracle_account.expect("dispensing_custody_oracle_account is not set"),
                      };
          let args = GetSwapAmountAndFeesInstructionArgs {
                                                              params: self.params.clone().expect("params is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `get_swap_amount_and_fees` CPI accounts.
  pub struct GetSwapAmountAndFeesCpiAccounts<'a, 'b> {
          
                    
              pub perpetuals: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub pool: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub receiving_custody: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub receiving_custody_oracle_account: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub dispensing_custody: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub dispensing_custody_oracle_account: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `get_swap_amount_and_fees` CPI instruction.
pub struct GetSwapAmountAndFeesCpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub perpetuals: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub pool: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub receiving_custody: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub receiving_custody_oracle_account: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub dispensing_custody: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub dispensing_custody_oracle_account: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: GetSwapAmountAndFeesInstructionArgs,
  }

impl<'a, 'b> GetSwapAmountAndFeesCpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: GetSwapAmountAndFeesCpiAccounts<'a, 'b>,
              args: GetSwapAmountAndFeesInstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              perpetuals: accounts.perpetuals,
              pool: accounts.pool,
              receiving_custody: accounts.receiving_custody,
              receiving_custody_oracle_account: accounts.receiving_custody_oracle_account,
              dispensing_custody: accounts.dispensing_custody,
              dispensing_custody_oracle_account: accounts.dispensing_custody_oracle_account,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(6 + remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.perpetuals.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.pool.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.receiving_custody.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.receiving_custody_oracle_account.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.dispensing_custody.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.dispensing_custody_oracle_account.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = GetSwapAmountAndFeesInstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::PERPETUALS_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(6 + 1 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.perpetuals.clone());
                        account_infos.push(self.pool.clone());
                        account_infos.push(self.receiving_custody.clone());
                        account_infos.push(self.receiving_custody_oracle_account.clone());
                        account_infos.push(self.dispensing_custody.clone());
                        account_infos.push(self.dispensing_custody_oracle_account.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `GetSwapAmountAndFees` via CPI.
///
/// ### Accounts:
///
          ///   0. `[]` perpetuals
          ///   1. `[]` pool
          ///   2. `[]` receiving_custody
          ///   3. `[]` receiving_custody_oracle_account
          ///   4. `[]` dispensing_custody
          ///   5. `[]` dispensing_custody_oracle_account
#[derive(Clone, Debug)]
pub struct GetSwapAmountAndFeesCpiBuilder<'a, 'b> {
  instruction: Box<GetSwapAmountAndFeesCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> GetSwapAmountAndFeesCpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(GetSwapAmountAndFeesCpiBuilderInstruction {
      __program: program,
              perpetuals: None,
              pool: None,
              receiving_custody: None,
              receiving_custody_oracle_account: None,
              dispensing_custody: None,
              dispensing_custody_oracle_account: None,
                                            params: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn perpetuals(&mut self, perpetuals: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.perpetuals = Some(perpetuals);
                    self
    }
      #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.pool = Some(pool);
                    self
    }
      #[inline(always)]
    pub fn receiving_custody(&mut self, receiving_custody: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiving_custody = Some(receiving_custody);
                    self
    }
      #[inline(always)]
    pub fn receiving_custody_oracle_account(&mut self, receiving_custody_oracle_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.receiving_custody_oracle_account = Some(receiving_custody_oracle_account);
                    self
    }
      #[inline(always)]
    pub fn dispensing_custody(&mut self, dispensing_custody: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.dispensing_custody = Some(dispensing_custody);
                    self
    }
      #[inline(always)]
    pub fn dispensing_custody_oracle_account(&mut self, dispensing_custody_oracle_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.dispensing_custody_oracle_account = Some(dispensing_custody_oracle_account);
                    self
    }
                    #[inline(always)]
      pub fn params(&mut self, params: GetSwapAmountAndFeesParams) -> &mut Self {
        self.instruction.params = Some(params);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = GetSwapAmountAndFeesInstructionArgs {
                                                              params: self.instruction.params.clone().expect("params is not set"),
                                    };
        let instruction = GetSwapAmountAndFeesCpi {
        __program: self.instruction.__program,
                  
          perpetuals: self.instruction.perpetuals.expect("perpetuals is not set"),
                  
          pool: self.instruction.pool.expect("pool is not set"),
                  
          receiving_custody: self.instruction.receiving_custody.expect("receiving_custody is not set"),
                  
          receiving_custody_oracle_account: self.instruction.receiving_custody_oracle_account.expect("receiving_custody_oracle_account is not set"),
                  
          dispensing_custody: self.instruction.dispensing_custody.expect("dispensing_custody is not set"),
                  
          dispensing_custody_oracle_account: self.instruction.dispensing_custody_oracle_account.expect("dispensing_custody_oracle_account is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct GetSwapAmountAndFeesCpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            perpetuals: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                pool: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                receiving_custody: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                receiving_custody_oracle_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                dispensing_custody: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                dispensing_custody_oracle_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        params: Option<GetSwapAmountAndFeesParams>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

