//! This code was AUTOGENERATED using the kinobi library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun kinobi to update it.
//!
//! <https://github.com/kinobi-so/kinobi>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateDecreasePositionMarketRequestParams {
pub collateral_usd_delta: u64,
pub size_usd_delta: u64,
pub price_slippage: u64,
pub jupiter_minimum_out: Option<u64>,
pub entire_position: Option<bool>,
pub counter: u64,
}


