//! This code was AUTOGENERATED using the kinobi library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun kinobi to update it.
//!
//! <https://github.com/kinobi-so/kinobi>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PnlAndFee {
pub has_profit: bool,
pub pnl_delta: u64,
pub open_position_fee_usd: u64,
pub close_position_fee_usd: u64,
pub funding_fee_usd: u64,
pub liquidation_price: u64,
}


